server {
    listen       80;
    server_name  studylandsedu.com localhost;

    # 设置网站根目录为当前项目目录
    root /Users/evanxu/Desktop/Github/studylandsedu;
    
    # 默认首页
    index index.html;

    # 地图瓦片数据代理
    location /_AMapService/maps {
        proxy_pass https://webrd01.is.autonavi.com/appmaptile;
        proxy_set_header Host webrd01.is.autonavi.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 卫星图像代理
    location /_AMapService/satellite {
        proxy_pass https://webst01.is.autonavi.com/appmaptile;
        proxy_set_header Host webst01.is.autonavi.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 自定义地图服务代理
    location /_AMapService/v4/map/styles {
        proxy_pass https://webapi.amap.com/v4/map/styles;
        proxy_set_header Host webapi.amap.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        set $args "$args&jscode=069054c71f549496597ba904d2e0b7e7";
    }

    # 海外地图服务代理
    location /_AMapService/v3/vectormap {
        proxy_pass https://fmap01.amap.com/v3/vectormap;
        proxy_set_header Host fmap01.amap.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        set $args "$args&jscode=069054c71f549496597ba904d2e0b7e7";
    }

    # Web服务API 代理
    location /_AMapService/ {
        proxy_pass https://restapi.amap.com/;
        proxy_set_header Host restapi.amap.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        set $args "$args&jscode=069054c71f549496597ba904d2e0b7e7";
    }

    # 处理静态文件
    location /assets {
        alias /Users/evanxu/Desktop/Github/studylandsedu/assets;
        expires 7d;
        add_header Cache-Control public;
    }

    # 其他通用配置
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 错误页面配置
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
} 